name: 'CI/CD'
on:
  push:
    branches:
      - bb

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Check types
        run: npm run typecheck

      - name: Run tests
        run: npm run test:coverage

      - name: Ensure build & shrinkwrap work
        run: npm run build && npm run package